name: 🔄 CI · Main

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: Ref.
        required: false
        default: ''
        type: string

permissions: {}

concurrency:
  group: build-main-${{ github.ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
    uses: YunaBraska/YunaBraska/.github/workflows/wc_node_build_common.yml@16d5a914c8cf8c94fdec88717c74017e1a9226e5
    with:
      ref: ${{ inputs.ref || github.sha }}
